#!/bin/sh
echo "This script allows root access to customer machines by Clearpath Robotics employees."
echo "Please instruct customer to run remote access script"
echo "Enter username of remote machine: "
read USERNAME
export REMOTE_PORT=10012
ssh ${USERNAME}@harvey.local -p ${REMOTE_PORT}
