#!/bin/sh
echo "This script allows root access to this machine by Clearpath Robotics employees."
echo "Please log in with password \"clearpath\" and await instructions."
echo "To shut down, press CTRL-C"
export REMOTE_PORT=10012
ssh -N -R ${REMOTE_PORT}:localhost:22 remoteassist@internal.clearpathrobotics.com -p 1222 -oStrictHostKeyChecking=no -oCheckHostIP=no
