#!/bin/sh
echo "This script allows access to customer machines by Clearpath Robotics employees."
echo "Please instruct customer to run remote access script"
echo "Enter username of remote machine (ex. \"turtlebot\" for TurtleBots): "
read USERNAME
export REMOTE_PORT=10012
ssh ${USERNAME}@localhost -p ${REMOTE_PORT}
